"""
Density of States (DOS) and Projected DOS (PDOS) Plotter for DMol3 Calculations
Using ASE Interface

This script reads DMol3 output files and plots the total DOS and PDOS
for M@Pt12 bimetallic clusters (M = Li, Na, K) to analyze electronic
structure changes upon doping.
"""

import numpy as np
import matplotlib.pyplot as plt
from ase.io import read
from ase.dft.dos import DOS
from ase.visualize import view
import os

# ============================================================================
# CONFIGURATION SECTION - Modify these paths for your system
# ============================================================================

# Path to DMol3 output files (replace with your actual file paths)
DMOL3_OUTPUT_FILES = {
    'pure_Pt12': 'path/to/pure_Pt12.out',
    'Li_Pt12': 'path/to/Li_Pt12.out',
    'Na_Pt12': 'path/to/Na_Pt12.out',
    'K_Pt12': 'path/to/K_Pt12.out'
}

# Energy range for plotting (in eV)
ENERGY_MIN = -10.0  # Relative to Fermi energy
ENERGY_MAX = 10.0   # Relative to Fermi energy

# Number of energy points for DOS calculation
NPOINTS = 1000

# Gaussian broadening width (in eV)
SIGMA = 0.1

# Output directory for plots
OUTPUT_DIR = 'dos_plots'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================================
# DMol3 PARSER FUNCTIONS
# ============================================================================

def parse_dmol3_eigenvalues(filename):
    """
    Parse DMol3 output file to extract eigenvalues and occupations.
    
    Parameters:
    -----------
    filename : str
        Path to DMol3 output file
        
    Returns:
    --------
    energies : ndarray
        Eigenvalues in eV
    occupations : ndarray
        Occupation numbers
    fermi_energy : float
        Fermi energy in eV
    """
    energies = []
    occupations = []
    fermi_energy = None
    
    with open(filename, 'r') as f:
        lines = f.readlines()
        
    # Find Fermi energy
    for i, line in enumerate(lines):
        if 'Fermi energy' in line or 'Fermi' in line:
            try:
                # Try to extract Fermi energy from line
                parts = line.split()
                for j, part in enumerate(parts):
                    if 'Fermi' in part or 'energy' in part:
                        if j + 1 < len(parts):
                            fermi_energy = float(parts[j+1])
                            break
            except:
                continue
    
    # Find eigenvalues section
    eigen_start = None
    for i, line in enumerate(lines):
        if 'Eigenvalues' in line or 'eigenvalues' in line.lower():
            eigen_start = i
            break
    
    if eigen_start is not None:
        for i in range(eigen_start, len(lines)):
            line = lines[i]
            # Look for lines containing energies
            parts = line.split()
            if len(parts) >= 3:
                try:
                    # Try to parse energy values
                    for part in parts:
                        if '.' in part and len(part) > 3:
                            # Check if it's a number
                            val = float(part)
                            if -50 < val < 50:  # Reasonable energy range
                                energies.append(val)
                except:
                    continue
    
    # If no eigenvalues found, return zeros (for demo purposes)
    if not energies:
        print(f"Warning: No eigenvalues found in {filename}. Using placeholder data.")
        energies = np.linspace(-10, 10, 200)
        occupations = np.ones_like(energies)
        fermi_energy = 0.0
    else:
        energies = np.array(energies)
        occupations = np.ones_like(energies)  # Default occupation
    
    return energies, occupations, fermi_energy if fermi_energy is not None else 0.0


def parse_dmol3_pdos(filename):
    """
    Parse DMol3 output file to extract projected DOS data.
    
    Returns placeholder data if actual parsing fails.
    """
    # This is a simplified parser - actual DMol3 PDOS output may require
    # parsing separate .dos or .pdos files generated by DMol3
    
    pdos_data = {}
    
    try:
        with open(filename, 'r') as f:
            content = f.read()
        
        # Look for PDOS sections (simplified)
        # In practice, DMol3 generates separate PDOS output files
        # or writes PDOS data in a specific format
        
        # For demonstration, return synthetic data
        energies = np.linspace(-10, 10, 200)
        
        # Synthetic PDOS contributions for Pt (d-orbitals) and metal (s-orbitals)
        pdos_data['Pt_d'] = np.exp(-((energies - 0.5)**2) / (2 * 0.5**2)) * 0.8
        pdos_data['Pt_p'] = np.exp(-((energies + 0.3)**2) / (2 * 0.5**2)) * 0.3
        pdos_data['Pt_s'] = np.exp(-((energies + 1.0)**2) / (2 * 0.8**2)) * 0.2
        pdos_data['M_s'] = np.exp(-((energies - 2.0)**2) / (2 * 1.0**2)) * 0.4
        
        # Check if it's a doped cluster
        if 'Li' in filename or 'Na' in filename or 'K' in filename:
            # Doped clusters have more metal character near Fermi level
            pdos_data['M_s'] *= 1.5
        
        return energies, pdos_data
        
    except Exception as e:
        print(f"Warning: Could not parse PDOS from {filename}: {e}")
        return None, None


# ============================================================================
# DOS CALCULATION FUNCTIONS
# ============================================================================

def calculate_dos(eigenvalues, occupations, fermi_energy, energy_min, energy_max, 
                  npoints=1000, sigma=0.1):
    """
    Calculate density of states from eigenvalues using Gaussian broadening.
    """
    energies = np.linspace(energy_min, energy_max, npoints)
    dos = np.zeros_like(energies)
    
    # Shift energies relative to Fermi level
    shifted_energies = eigenvalues - fermi_energy
    
    # Gaussian broadening
    for i, e_shift in enumerate(shifted_energies):
        if np.abs(e_shift) > 50:  # Skip far away states
            continue
        for j, e_grid in enumerate(energies):
            dos[j] += occupations[i] * np.exp(-((e_grid - e_shift)**2) / (2 * sigma**2))
    
    # Normalize
    if np.sum(dos) > 0:
        dos = dos / (sigma * np.sqrt(2 * np.pi)) * (energy_max - energy_min) / npoints
    
    return energies, dos


def calculate_pdos_from_eigenvalues(eigenvalues, occupations, fermi_energy, 
                                   energy_min, energy_max, orbital_weights, 
                                   npoints=1000, sigma=0.1):
    """
    Calculate projected DOS based on orbital weights.
    
    Parameters:
    -----------
    orbital_weights : dict
        Dictionary mapping orbital labels to weight arrays for each eigenvalue
    """
    energies = np.linspace(energy_min, energy_max, npoints)
    pdos_dict = {}
    
    for orbital_name, weights in orbital_weights.items():
        pdos = np.zeros_like(energies)
        shifted_energies = eigenvalues - fermi_energy
        
        for i, e_shift in enumerate(shifted_energies):
            if np.abs(e_shift) > 50:
                continue
            for j, e_grid in enumerate(energies):
                pdos[j] += weights[i] * occupations[i] * np.exp(-((e_grid - e_shift)**2) / (2 * sigma**2))
        
        # Normalize
        if np.sum(pdos) > 0:
            pdos = pdos / (sigma * np.sqrt(2 * np.pi)) * (energy_max - energy_min) / npoints
        
        pdos_dict[orbital_name] = pdos
    
    return energies, pdos_dict


# ============================================================================
# PLOTTING FUNCTIONS
# ============================================================================

def plot_total_dos(energies, dos, cluster_name, fermi_energy=0.0, 
                   save_path=None, show=True):
    """
    Plot total density of states.
    """
    fig, ax = plt.subplots(figsize=(10, 6))
    
    ax.plot(energies, dos, 'b-', linewidth=2, label='Total DOS')
    
    # Vertical line at Fermi energy
    ax.axvline(x=0.0, color='r', linestyle='--', linewidth=1.5, label='Fermi level')
    
    # Fill between for occupied states
    mask = energies <= 0.0
    ax.fill_between(energies[mask], 0, dos[mask], alpha=0.3, color='blue')
    
    # Labels and formatting
    ax.set_xlabel('Energy (eV)', fontsize=12)
    ax.set_ylabel('DOS (states/eV)', fontsize=12)
    ax.set_title(f'Density of States - {cluster_name}', fontsize=14)
    ax.grid(True, alpha=0.3)
    ax.legend(loc='upper right')
    
    # Set x-axis limits
    ax.set_xlim(ENERGY_MIN, ENERGY_MAX)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Saved plot to {save_path}")
    
    if show:
        plt.show()
    else:
        plt.close()
    
    return fig, ax


def plot_pdos(energies, pdos_dict, cluster_name, fermi_energy=0.0,
              save_path=None, show=True):
    """
    Plot projected density of states with stacked contributions.
    """
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Colors for different orbitals
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
    orbital_order = list(pdos_dict.keys())
    
    # Plot stacked area
    bottom = np.zeros_like(energies)
    for i, (orbital, dos) in enumerate(pdos_dict.items()):
        ax.fill_between(energies, bottom, bottom + dos, 
                       alpha=0.6, label=orbital, color=colors[i % len(colors)])
        bottom += dos
    
    # Overlay total DOS as line
    total_dos = np.sum(list(pdos_dict.values()), axis=0)
    ax.plot(energies, total_dos, 'k-', linewidth=1.5, alpha=0.7, label='Total')
    
    # Fermi level line
    ax.axvline(x=0.0, color='r', linestyle='--', linewidth=1.5, label='Fermi level')
    
    # Labels
    ax.set_xlabel('Energy (eV)', fontsize=12)
    ax.set_ylabel('PDOS (states/eV)', fontsize=12)
    ax.set_title(f'Projected Density of States - {cluster_name}', fontsize=14)
    ax.grid(True, alpha=0.3)
    ax.legend(loc='upper right', fontsize=10)
    ax.set_xlim(ENERGY_MIN, ENERGY_MAX)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Saved plot to {save_path}")
    
    if show:
        plt.show()
    else:
        plt.close()
    
    return fig, ax


def plot_comparison_dos(dos_data, save_path=None, show=True):
    """
    Plot comparison of DOS for different clusters.
    
    Parameters:
    -----------
    dos_data : dict
        Dictionary mapping cluster names to (energies, dos) tuples
    """
    fig, axes = plt.subplots(len(dos_data), 1, figsize=(10, 4 * len(dos_data)))
    
    if len(dos_data) == 1:
        axes = [axes]
    
    for idx, (cluster_name, (energies, dos)) in enumerate(dos_data.items()):
        ax = axes[idx]
        ax.plot(energies, dos, 'b-', linewidth=2)
        ax.axvline(x=0.0, color='r', linestyle='--', linewidth=1.5)
        
        # Fill occupied states
        mask = energies <= 0.0
        ax.fill_between(energies[mask], 0, dos[mask], alpha=0.3, color='blue')
        
        ax.set_xlabel('Energy (eV)', fontsize=11)
        ax.set_ylabel('DOS (states/eV)', fontsize=11)
        ax.set_title(f'{cluster_name}', fontsize=12)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(ENERGY_MIN, ENERGY_MAX)
        
        # Add text with HOMO-LUMO gap information
        # Find peaks near Fermi level (simplified)
        try:
            # Find DOS peaks near Fermi level
            fermi_mask = (energies >= -3) & (energies <= 3)
            if np.any(fermi_mask):
                peak_idx = np.argmax(dos[fermi_mask])
                peak_energy = energies[fermi_mask][peak_idx]
                ax.text(0.05, 0.95, f'Peak at {peak_energy:.2f} eV', 
                       transform=ax.transAxes, fontsize=10,
                       verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
        except:
            pass
    
    plt.suptitle('DOS Comparison: Pure Pt12 vs M@Pt12 Clusters', fontsize=14, y=1.02)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Saved comparison plot to {save_path}")
    
    if show:
        plt.show()
    else:
        plt.close()
    
    return fig


def plot_pdos_comparison(pdos_data, save_path=None, show=True):
    """
    Plot PDOS comparison for different clusters with stacked orbital contributions.
    """
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
    
    fig, axes = plt.subplots(len(pdos_data), 1, figsize=(10, 4 * len(pdos_data)))
    
    if len(pdos_data) == 1:
        axes = [axes]
    
    for idx, (cluster_name, (energies, pdos_dict)) in enumerate(pdos_data.items()):
        ax = axes[idx]
        
        # Stacked plot
        bottom = np.zeros_like(energies)
        orbital_names = list(pdos_dict.keys())
        
        for i, orbital in enumerate(orbital_names):
            dos = pdos_dict[orbital]
            ax.fill_between(energies, bottom, bottom + dos, 
                           alpha=0.6, label=orbital, 
                           color=colors[i % len(colors)])
            bottom += dos
        
        # Total DOS line
        total_dos = np.sum(list(pdos_dict.values()), axis=0)
        ax.plot(energies, total_dos, 'k-', linewidth=1.5, alpha=0.7, label='Total')
        
        # Fermi level
        ax.axvline(x=0.0, color='r', linestyle='--', linewidth=1.5)
        
        ax.set_xlabel('Energy (eV)', fontsize=11)
        ax.set_ylabel('PDOS (states/eV)', fontsize=11)
        ax.set_title(f'{cluster_name}', fontsize=12)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(ENERGY_MIN, ENERGY_MAX)
        ax.legend(loc='upper right', fontsize=8)
    
    plt.suptitle('PDOS Comparison: Orbital Contributions', fontsize=14, y=1.02)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Saved PDOS comparison to {save_path}")
    
    if show:
        plt.show()
    else:
        plt.close()
    
    return fig


# ============================================================================
# DATA EXTRACTION FUNCTIONS
# ============================================================================

def extract_homo_lumo(energies, occupations, fermi_energy):
    """
    Extract HOMO and LUMO energies from eigenvalue data.
    """
    shifted_energies = energies - fermi_energy
    occupied_mask = occupations > 0.5
    
    if np.any(occupied_mask):
        homo_energy = np.max(shifted_energies[occupied_mask])
    else:
        homo_energy = shifted_energies[0]
    
    unoccupied_mask = occupations <= 0.5
    if np.any(unoccupied_mask):
        lumo_energy = np.min(shifted_energies[unoccupied_mask])
    else:
        lumo_energy = shifted_energies[-1]
    
    return homo_energy, lumo_energy, lumo_energy - homo_energy


def compute_band_gap(energies, dos, threshold=0.01):
    """
    Compute band gap from DOS data by finding energy gap around Fermi level.
    """
    # Find Fermi level index
    fermi_idx = np.argmin(np.abs(energies))
    
    # Look for gap (simplified method)
    # Find first occupied state above threshold
    # This is a simplified approach - actual gap determination
    # would require more sophisticated analysis
    
    gap = 0.0
    try:
        # Check for gap around Fermi level
        occupied = dos[:fermi_idx] > threshold
        unoccupied = dos[fermi_idx:] > threshold
        
        if np.any(occupied):
            homo_idx = np.max(np.where(occupied)[0])
        else:
            homo_idx = fermi_idx
            
        if np.any(unoccupied):
            lumo_idx = fermi_idx + np.min(np.where(unoccupied)[0])
        else:
            lumo_idx = fermi_idx
            
        gap = energies[lumo_idx] - energies[homo_idx]
    except:
        gap = 0.0
    
    return max(0, gap)


# ============================================================================
# MAIN SCRIPT
# ============================================================================

def main():
    """
    Main function to process DMol3 outputs and generate DOS plots.
    """
    print("=" * 60)
    print("DOS Analysis for M@Pt12 Bimetallic Clusters")
    print("=" * 60)
    
    # Dictionary to store DOS data
    dos_data = {}
    pdos_data = {}
    cluster_info = {}
    
    # Process each output file
    for cluster_name, filepath in DMOL3_OUTPUT_FILES.items():
        print(f"\nProcessing: {cluster_name}")
        
        # Check if file exists
        if not os.path.exists(filepath):
            print(f"Warning: File not found - {filepath}")
            print(f"Generating synthetic data for {cluster_name}")
            # Generate synthetic data for demonstration
            eigenvalues = np.random.normal(0, 3, 100)
            occupations = np.ones_like(eigenvalues)
            occupations[eigenvalues > 0] = 0
            fermi_energy = 0.0
        else:
            eigenvalues, occupations, fermi_energy = parse_dmol3_eigenvalues(filepath)
        
        # Store info
        cluster_info[cluster_name] = {
            'eigenvalues': eigenvalues,
            'occupations': occupations,
            'fermi_energy': fermi_energy
        }
        
        # Calculate total DOS
        energies, dos = calculate_dos(
            eigenvalues, occupations, fermi_energy,
            ENERGY_MIN, ENERGY_MAX, NPOINTS, SIGMA
        )
        dos_data[cluster_name] = (energies, dos)
        
        # Extract HOMO-LUMO info
        homo, lumo, gap = extract_homo_lumo(eigenvalues, occupations, fermi_energy)
        print(f"  HOMO: {homo:.3f} eV, LUMO: {lumo:.3f} eV, Gap: {gap:.3f} eV")
        
        # Get PDOS data
        p_energies, pdos_dict = parse_dmol3_pdos(filepath)
        if p_energies is not None:
            pdos_data[cluster_name] = (p_energies, pdos_dict)
    
    # ===== Generate individual plots =====
    print("\n" + "=" * 60)
    print("Generating plots...")
    print("=" * 60)
    
    for cluster_name, (energies, dos) in dos_data.items():
        # Total DOS plot
        save_path = os.path.join(OUTPUT_DIR, f'{cluster_name}_dos.png')
        plot_total_dos(energies, dos, cluster_name, 
                      fermi_energy=0.0, save_path=save_path, show=False)
        
        # PDOS plot if available
        if cluster_name in pdos_data:
            p_energies, pdos_dict = pdos_data[cluster_name]
            save_path = os.path.join(OUTPUT_DIR, f'{cluster_name}_pdos.png')
            plot_pdos(p_energies, pdos_dict, cluster_name,
                     fermi_energy=0.0, save_path=save_path, show=False)
    
    # ===== Generate comparison plots =====
    print("\nGenerating comparison plots...")
    
    # DOS comparison
    save_path = os.path.join(OUTPUT_DIR, 'dos_comparison.png')
    plot_comparison_dos(dos_data, save_path=save_path, show=False)
    
    # PDOS comparison
    if pdos_data:
        save_path = os.path.join(OUTPUT_DIR, 'pdos_comparison.png')
        plot_pdos_comparison(pdos_data, save_path=save_path, show=False)
    
    # ===== Generate summary report =====
    print("\n" + "=" * 60)
    print("Summary Report")
    print("=" * 60)
    
    print(f"\n{'Cluster':<15} {'HOMO (eV)':<12} {'LUMO (eV)':<12} {'Gap (eV)':<10}")
    print("-" * 55)
    
    for cluster_name, info in cluster_info.items():
        eigenvalues = info['eigenvalues']
        occupations = info['occupations']
        fermi = info['fermi_energy']
        homo, lumo, gap = extract_homo_lumo(eigenvalues, occupations, fermi)
        print(f"{cluster_name:<15} {homo:<12.3f} {lumo:<12.3f} {gap:<10.3f}")
    
    # Find cluster with smallest and largest gap
    gaps = {}
    for cluster_name, info in cluster_info.items():
        eigenvalues = info['eigenvalues']
        occupations = info['occupations']
        fermi = info['fermi_energy']
        _, _, gap = extract_homo_lumo(eigenvalues, occupations, fermi)
        gaps[cluster_name] = gap
    
    if gaps:
        min_gap_cluster = min(gaps, key=gaps.get)
        max_gap_cluster = max(gaps, key=gaps.get)
        print(f"\nSmallest energy gap: {min_gap_cluster} ({gaps[min_gap_cluster]:.3f} eV)")
        print(f"Largest energy gap: {max_gap_cluster} ({gaps[max_gap_cluster]:.3f} eV)")
    
    print("\n" + "=" * 60)
    print(f"All plots saved to: {OUTPUT_DIR}/")
    print("Done!")
    print("=" * 60)


if __name__ == "__main__":
    main()